openapi: 3.0.0
info:
  title: SUW API
  version: 0.1.0
servers:
  - url: http://localhost:8000/
    description: Local
  - url: http://producation.app/
    description: Production
paths:
  /takeword:
    get:
      summary: Returns a list of users.
      responses:
        '200':
          description: A JSON array of user names
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
